import type { BusStop } from '../types'

export const route02: BusStop[] = [
  // Stops 1-3: Heavy boarding, minimal alighting → build up fast
  {
    id: 1,
    name: 'Bác Cổ (Trần Khánh Dư)',
    difficulty: 1,
    boardMin: 6,
    boardMax: 9,
    alightMin: 0,
    alightMax: 0,
  },
  {
    id: 2,
    name: 'Trần Khánh Dư',
    difficulty: 2,
    boardMin: 5,
    boardMax: 8,
    alightMin: 0,
    alightMax: 1,
  },
  {
    id: 3,
    name: 'Trần Hưng Đạo',
    difficulty: 2,
    boardMin: 5,
    boardMax: 8,
    alightMin: 0,
    alightMax: 2,
  },
  // Stops 4-5: Still strong boarding, light alighting
  {
    id: 4,
    name: 'Lê Thánh Tông',
    difficulty: 2,
    boardMin: 5,
    boardMax: 8,
    alightMin: 1,
    alightMax: 3,
  },
  {
    id: 5,
    name: 'Hai Bà Trưng',
    difficulty: 3,
    boardMin: 5,
    boardMax: 9,
    alightMin: 1,
    alightMax: 3,
  },
  // Stops 6-8: Peak zone — bus should be ~28-32 passengers
  {
    id: 6,
    name: 'Quang Trung',
    difficulty: 3,
    boardMin: 4,
    boardMax: 7,
    alightMin: 2,
    alightMax: 4,
  },
  { id: 7, name: 'Tràng Thi', difficulty: 3, boardMin: 4, boardMax: 7, alightMin: 2, alightMax: 5 },
  {
    id: 8,
    name: 'Điện Biên Phủ',
    difficulty: 4,
    boardMin: 4,
    boardMax: 7,
    alightMin: 3,
    alightMax: 6,
  },
  // Stops 9-12: Plateau — boarding ≈ alighting, stays crowded
  { id: 9, name: 'Trần Phú', difficulty: 4, boardMin: 5, boardMax: 8, alightMin: 4, alightMax: 7 },
  {
    id: 10,
    name: 'Chu Văn An',
    difficulty: 4,
    boardMin: 5,
    boardMax: 9,
    alightMin: 5,
    alightMax: 8,
  },
  {
    id: 11,
    name: 'Tôn Đức Thắng',
    difficulty: 4,
    boardMin: 5,
    boardMax: 9,
    alightMin: 5,
    alightMax: 9,
  },
  {
    id: 12,
    name: 'Nguyễn Lương Bằng',
    difficulty: 5,
    boardMin: 6,
    boardMax: 10,
    alightMin: 5,
    alightMax: 9,
  },
  // Stops 13-16: Gradual decline
  { id: 13, name: 'Tây Sơn', difficulty: 5, boardMin: 5, boardMax: 9, alightMin: 6, alightMax: 10 },
  {
    id: 14,
    name: 'Ngã tư Sở',
    difficulty: 5,
    boardMin: 5,
    boardMax: 9,
    alightMin: 6,
    alightMax: 10,
  },
  {
    id: 15,
    name: 'Nguyễn Trãi',
    difficulty: 5,
    boardMin: 5,
    boardMax: 8,
    alightMin: 7,
    alightMax: 11,
  },
  {
    id: 16,
    name: 'Trần Phú (Hà Đông)',
    difficulty: 5,
    boardMin: 4,
    boardMax: 8,
    alightMin: 7,
    alightMax: 12,
  },
  // Stops 17-19: Wind down
  {
    id: 17,
    name: 'Quang Trung (Hà Đông)',
    difficulty: 5,
    boardMin: 3,
    boardMax: 6,
    alightMin: 8,
    alightMax: 12,
  },
  { id: 18, name: 'Ba La', difficulty: 5, boardMin: 2, boardMax: 5, alightMin: 8, alightMax: 13 },
  {
    id: 19,
    name: 'Quốc Lộ 6',
    difficulty: 5,
    boardMin: 1,
    boardMax: 4,
    alightMin: 10,
    alightMax: 15,
  },
  // Terminal
  {
    id: 20,
    name: 'BX Yên Nghĩa',
    difficulty: 5,
    boardMin: 0,
    boardMax: 0,
    alightMin: 0,
    alightMax: 0,
  },
]

export const DIFFICULTY_MULTIPLIER: Record<number, number> = {
  1: 1.0,
  2: 1.25,
  3: 1.5,
  4: 2.0,
  5: 2.5,
}
